export const DISTRICTS_CITIES: Record<string, string[]> = {
  "Colombo": ["Colombo 01-15", "Dehiwala", "Mount Lavinia", "Moratuwa", "Kotte", "Maharagama", "Kesbewa", "Battaramulla", "Kaduwela", "Homagama", "Kolonnawa", "Hanwella", "Avissawella", "Padukka", "Mulleriyawa", "Malabe", "Athurugiriya", "Pannipitiya", "Rajagiriya", "Nugegoda", "Kottawa"],
  "Gampaha": ["Gampaha", "Negombo", "Katunayake", "Wattala", "Kelaniya", "Ja-Ela", "Kadawatha", "Kiribathgoda", "Ragama", "Biyagama", "Delgoda", "Divulapitiya", "Mirigama", "Minuwangoda", "Veyangoda", "Nittambuwa", "Kirindiwela", "Ganemulla", "Kandana"],
  "Kalutara": ["Kalutara", "Panadura", "Horana", "Beruwala", "Matugama", "Aluthgama", "Bandaragama", "Wadduwa", "Agalawatte", "Bulathsinhala", "Dodangoda", "Ingiriya", "Paiyagala"],
  "Kandy": ["Kandy", "Peradeniya", "Katugastota", "Gampola", "Nawalapitiya", "Wattegama", "Kundasale", "Akurana", "Digana", "Kadugannawa", "Madawala", "Teldeniya", "Pilimathalawa", "Menikhinna", "Galagedara"],
  "Galle": ["Galle", "Hikkaduwa", "Karapitiya", "Ambalangoda", "Elpitiya", "Baddegama", "Bentota", "Habaraduwa", "Hiniduma", "Neluwa", "Ahangama", "Batapola", "Karandeniya"],
  "Matara": ["Matara", "Weligama", "Akuressa", "Dickwella", "Deniyaya", "Kamburupitiya", "Kekanadurra", "Kotapola", "Hakmana", "Gandara", "Kamburugamuwa"],
  "Kurunegala": ["Kurunegala", "Kuliyapitiya", "Narammala", "Wariyapola", "Pannala", "Alawwa", "Bingiriya", "Galgamuwa", "Giriulla", "Hettipola", "Ibbagamuwa", "Mawathagama", "Polgahawela", "Nikaweratiya", "Maho"],
  "Anuradhapura": ["Anuradhapura", "Eppawala", "Mihintale", "Kekirawa", "Thalawa", "Habarana", "Medawachchiya", "Padaviya", "Tambuttegama", "Galenbindunuwewa", "Nochchiyagama"],
  "Ratnapura": ["Ratnapura", "Balangoda", "Eheliyagoda", "Kuruwita", "Pelmadulla", "Embilipitiya", "Godakawela", "Kalawana", "Rakwana", "Ayagama", "Kahawatta", "Pannala"],
  "Kegalle": ["Kegalle", "Mawanella", "Warakapola", "Rambukkana", "Dehiowita", "Deraniyagala", "Galigamuwa", "Kitulgala", "Ruwanwella", "Yatiyantota", "Bulathkohupitiya"],
  "Badulla": ["Badulla", "Bandarawela", "Hali-Ela", "Haputale", "Mahiyanganaya", "Welimada", "Diyatalawa", "Ella", "Passara", "Lunugala"],
  "Hambantota": ["Hambantota", "Tangalle", "Beliatta", "Ambalantota", "Tissamaharama", "Angunakolapelessa", "Kataragama", "Walasmulla", "Weeraketiya", "Middeniya"],
  "Puttalam": ["Puttalam", "Chilaw", "Wennappuwa", "Marawila", "Dankotuwa", "Anamaduwa", "Kalpitiya", "Madampe", "Nattandiya", "Mundel"],
  "Jaffna": ["Jaffna", "Chavakachcheri", "Point Pedro", "Nallur", "Chunnakam", "Karainagar", "Kayts", "Kopay", "Tellippalai", "Vaddukoddai", "Manipay"],
  "Trincomalee": ["Trincomalee", "Kinniya", "Mutur", "Kantale", "Kuchchaveli", "Serunuwara"],
  "Batticaloa": ["Batticaloa", "Eravur", "Kattankudy", "Chenkalady", "Kaluwanchikudy", "Valaichchenai", "Oddamavadi"],
  "Ampara": ["Ampara", "Samanthurai", "Kalmunai", "Akkaraipattu", "Mahaoya", "Pottuvil", "Uhana", "Sainthamaruthu", "Dehiattakandiya"],
  "Matale": ["Matale", "Dambulla", "Sigiriya", "Galewela", "Rattota", "Ukuwela", "Pallepola", "Yatawatta"],
  "Nuwara Eliya": ["Nuwara Eliya", "Hatton", "Talawakele", "Ginigathena", "Kotmale", "Maskeliya", "Walapane", "Agrapatana", "Pundaluoya"],
  "Polonnaruwa": ["Polonnaruwa", "Kaduruwela", "Medirigiriya", "Hingurakgoda", "Welikanda", "Aralaganwila", "Bakamuna"],
  "Moneragala": ["Moneragala", "Wellawaya", "Buttala", "Bibile", "Kataragama", "Medagama", "Tanamanwila", "Siyambalanduwa"],
  "Vavuniya": ["Vavuniya", "Cheddikulam", "Nedunkeni"],
  "Mannar": ["Mannar", "Adampan", "Madhu", "Murunkan", "Nanattan", "Talaimannar"],
  "Mullaitivu": ["Mullaitivu", "Oddusuddan", "Puthukkudiyiruppu", "Mankulam", "Mallavi"],
  "Kilinochchi": ["Kilinochchi", "Paranthan", "Poonakary", "Pallai"]
};
